### ISSUE TITLE
Link no corresponde

### ISSUE THREAD

**Issue by verohy** [opensaludlab/ciencia_datos#1]
En Readme  del Módulo 1, apartado 5:
El link para la Lectura recomendada: "Una mirada a la cultura de datos en Chile. Ministerio de Ciencias y Tecnología. Chile" no lleva al documento, podría reemplazarse con el siguiente: https://www.minciencia.gob.cl/legacy-files/whitepaper_datos_covid19.pdf

**Comment by paulovillarroel** [comment]
Gracias! 
Arreglado
